### ISSUE TITLE
css not working behind reverse proxy

### ISSUE THREAD

**Issue by cybermcm** [manbearwiz/youtube-dl-server#113]
Using latest docker image with youtube-dl-server behind a reverse proxy (Traefik).
Webpage looks garbled because style.css couldn't be loaded (strict-origin-when-cross-origin)

css is loaded via http instead of https, but this is prohibited due to policy settings.

Not quite sure how other projects solve this, but I've many containers behind my reverse proxy and this error only happens here.
Any ideas how to solve this?

**Comment by DArtagan** [comment]
I hit the same snag.  It looks like this may be because uvicorn doesn't (by default) trust and pass on the incoming Forwarded headers.  I worked around this by tweaking the command line in my docker-compose file (and it would be much the same for running by CLI):
```
youtube-dl:
  image: kmb32123/youtube-dl-server:master
  command: ["uvicorn", "youtube-dl-server:app", "--host", "0.0.0.0", "--port", "8080", "--proxy-headers", "--forwarded-allow-ips", "*"]
```
It's safe for the `--forwarded-allow-ips` to be `*` only because I'm certain this container can only possibly be receiving traffic from the reverse-proxy and no where else.

**Comment by cybermcm** [comment]
@DArtagan This is a nice workaround! Can confirm that this works. Will leave this open until it is finally resolved

**Comment by pepitooo** [comment]
I had the same issue, and didn't look issues list first.

I come up with a similar solution, but more future proof if the command line change

```
  youtube-dl:
    image: "kmb32123/youtube-dl-server"
    environment:
      FORWARDED_ALLOW_IPS: '*'
```

**Comment by manbearwiz** [comment]
This should be fixed if you pull latest. I just inlined the styles. There are hardly any there and this way I don't have to validate on all possible configurations
