### ISSUE TITLE
[Feature] Add autoupdate on restart

### ISSUE THREAD

**Issue by RicardoVelaC** [manbearwiz/youtube-dl-server#30]
Please consider add autoupdate on a restart docker image for get the last youtube-dl version

**Comment by RicardoVelaC** [comment]
With image base [alpine:edge](https://pkgs.alpinelinux.org/packages?name=youtube-dl&branch=edge) you can get the latest package of youtube-dl

**Comment by manbearwiz** [comment]
I actually install youtube-dl through pip, not through the alpine packages. This should still get the latest version of youtube-dl on build though.

It feels a bit wrong to update a container instance rather than pull a new image in docker, but since the latest images aren't always up to date I could get behind this. I may look into just creating a `/update` endpoint on the server that will trigger a `pip install youtube-dl --upgrade`. Only risk I see here is if there are breaking changes in the youtube-dl api you may end up with a broken container.

**Comment by GlassedSilver** [comment]
> but since the latest images aren't always up to date I could get behind this.

To be frank, youtube-dl sometimes breaks within a day. Google isn't exactly bothered to support applications like these as we all know. They don't really fight youtube-dl as it seems, but they do not necessarily announce changes much in advance. Also, should this docker for whatever reason ever become deprecated at least the youtube-dl instance within would stay up to snuff until its dependencies change.

> Only risk I see here is if there are breaking changes in the youtube-dl api you may end up with a broken container.

True, that is a valid concern, but I think those zero-day incompatibilities with Youtube itself are a little more frequent.

**Comment by manbearwiz** [comment]
@jlnostr implemented this. Do either @RicardoVelaC or @GlassedSilver want to pull the latest image and keep me posted on if it is working for them? Thanks.
